---
- hosts: mediascape
  gather_facts: yes

  tasks:

    - name: apt package(s)
      apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - vim
          - git
      become: true

    - name: checkout source code
      git:
        repo: 'git@github.com:nickmpaz/mediascape.git'
        dest: '/home/ubuntu/mediascape'
        accept_hostkey: yes

    - name: docker-compose restart
      shell: docker-compose -f docker-compose.prod.yml down && docker-compose -f docker-compose.prod.yml up -d --build
      args:
        chdir: '/home/ubuntu/mediascape'