---
- hosts: mediascape
  gather_facts: yes
  # become: true

  tasks:

    - name: apt package(s)
      apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - vim
          - git

    - name: checkout source code
      git:
        repo: 'git@github.com:nickmpaz/mediascape.git'
        dest: '/home/ubuntu/mediascape'
        accept_hostkey: yes

    # - name: docker-compose restart
    #   command: 'docker-compose down && docker-compose -f docker-compose.prod.yml up -d --build'
    #     args:
    #       chdir: '/home/ubuntu/mediascape'

    # docker + docker-compose 
    # ensure mediascape repository is present 
    # ensure mediascape repository is up to date
    # docker-compose restart
    # migrate tables    